### ISSUE TITLE
installation, namespaces

### ISSUE THREAD

**Issue by larshp** [galileo-group/galileo-abap-lib#1]
hi,
will you be providing the key for the `/gal/` namespace, so users can install the code?

**Comment by thomas-erdoesi** [comment]
A very late answer: The repair license is "31892702823248560281".
We are currently working on an automatied way to keep a synchronized version of the code in the Z namespace to simplify installation.

**Comment by larshp** [comment]
thanks

for renaming, I'm working on standalone automated renaming of ABAP objects, see https://github.com/abapGit/odense-z/blob/main/abaplint_abapGit_zcl.json#L17 for an example, idea is it will be possible to mirror objects into a different namespace, eg running via github actions on every push

for now it kind of works for CLAS and INTF objects, more to be added

**Comment by thomas-erdoesi** [comment]
I like the idea of solving this via github actions but it might be hard to identify all the references between the objects...
Our approach will be implemented in ABAP and run on ABAP package level.
We are currently planning to make parts of our products open source, that's the reason to implement a renaming tool. I am currently not working on SAP projects but if you want I can connect you to our development team working on this.

**Comment by larshp** [comment]
difficult, yes, email me at larshp@hotmail.com

have most of the OO references done, see https://abaplint.app/stats/abapGit/abapGit/dependencies
